W0506 15:33:50.504000 34016 site-packages/torch/distributed/elastic/multiprocessing/redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
W0506 15:33:50.523000 34016 site-packages/torch/distributed/run.py:793] 
W0506 15:33:50.523000 34016 site-packages/torch/distributed/run.py:793] *****************************************
W0506 15:33:50.523000 34016 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0506 15:33:50.523000 34016 site-packages/torch/distributed/run.py:793] *****************************************
Traceback (most recent call last):
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/scripts/llama_ring/benchmark_ring.py", line 11, in <module>
    from fms import models
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/fms/models/__init__.py", line 496, in <module>
    from fms.models import bamba, gpt_bigcode, granite, llama, mixtral, roberta  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/fms/models/llama.py", line 67, in <module>
    class LLaMABlock(nn.Module):
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/fms/models/llama.py", line 69, in LLaMABlock
    compute_local_qkv_and_rope  = compute_local_qkv_and_rope
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'compute_local_qkv_and_rope' is not defined
Traceback (most recent call last):
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/scripts/llama_ring/benchmark_ring.py", line 11, in <module>
    from fms import models
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/fms/models/__init__.py", line 496, in <module>
    from fms.models import bamba, gpt_bigcode, granite, llama, mixtral, roberta  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/fms/models/llama.py", line 67, in <module>
    class LLaMABlock(nn.Module):
  File "/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/fms/models/llama.py", line 69, in LLaMABlock
    compute_local_qkv_and_rope  = compute_local_qkv_and_rope
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'compute_local_qkv_and_rope' is not defined
E0506 15:33:51.905000 34016 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 34020) of binary: /Users/sadigulcelik/anaconda3/bin/python
Traceback (most recent call last):
  File "/Users/sadigulcelik/anaconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.6.0.dev20241112', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sadigulcelik/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sadigulcelik/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/Users/sadigulcelik/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/Users/sadigulcelik/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sadigulcelik/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/Users/sadigulcelik/Documents/CompSci/HPML-2025-Spring/FMSwrapper/foundation-model-stack/scripts/llama_ring/benchmark_ring.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-06_15:33:51
  host      : mac.lan
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 34021)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-06_15:33:51
  host      : mac.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 34020)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
